### ISSUE TITLE
Replicaset should use namespaced hostnames for members

### ISSUE THREAD

**Issue by cwilkers** [skupperproject/skupper-example-mongodb-replica-set#1]
Using this example with an application in another namespace (our pacman demo in https://github.com/openshift/federation-dev/tree/master/federated-pacman), I found that pacman needed to refer to the service-name.namespace as the host name for members, e.g.
`mongo-svc-a.mongodb-replica-set-demo`

My application was then able to connect, but there was one more requirement, that the actual MongoDB rs config also use the namespaced hostnames.

It would be worth a mention in the docs that adding your namespace to the values in `replica.js`
is required if accessing mongo from outside its own namespace.

**Comment by ted-ross** [comment]
Did you consider putting the skupper artifacts into the same namespace as the pacman demo?

**Comment by cwilkers** [comment]
I'll give that a try.
